apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bases/manila
patches:
- path: multibackend.yaml
- patch: |-
    - op: replace
      path: /spec/secret
      value: osp-secret
    - op: replace
      path: /metadata/namespace
      value: manila-kuttl-tests
    - op: replace
      path: /spec/manilaShares/share1/replicas
      value: 0
  target:
    kind: Manila
