apiVersion: manila.openstack.org/v1beta1
kind: Manila
metadata:
  name: manila
  namespace: openstack
spec:
  serviceUser: manila
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  secret: osp-secret
  databaseUser: manila
  rabbitMqClusterName: rabbitmq
  manilaAPI:
    containerImage: quay.io/podified-antelope-centos9/openstack-manila-api:current-podified
  manilaScheduler:
    containerImage: quay.io/podified-antelope-centos9/openstack-manila-scheduler:current-podified
  manilaShares:
    share1:
      containerImage: quay.io/podified-antelope-centos9/openstack-manila-share:current-podified
